# Italian mobility changes, 2020

<br>

Google Mobility data was made available for COVID-19 research purposes, so it lacks dynamic controls.  
This dashboard solves this issue by providing an intuitive and easy to understand solution: it displays Google Mobility data but allows easy plot personalisation.  

### How it works

This dasboard is built as a `R` `shiny` app. It downloads Google Mobility data, processes it for plotting. Plots are rendered according to user preferences. Data is refreshed every week.  
Source code is available [here](https://github.com/ilcavaliereverde/ItalianMobility2020/); this project is licensed under the [MIT license](./license.Rmd). 

### Data 

Google harvests mobility data and compiles it into a `.csv` file, as explained in the [COVID-19 Community Mobility Reports](https://www.google.com/covid19/mobility/).  
You can download the `.csv` [here](ttps://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv) (**warning**: very large file, over 200 MB).  

### Plots 

Withing this dashboard, you can choose to plot:
* different start-end dates;
* different types of mobility change;
* different Italian regions and provinces.  
Plots are rendered as `.png` files and can be easily downloaded by right-clicking on the plot.

### Interpretation 

In order to correctly interpret plots, please read the simple and concise [Google Guide](https://support.google.com/covid19-mobility/answer/9824897?hl=en-GB&ref_topic=9822927) to Community Reports.  
Just a few of several notes: 

* change is relative to a baseline; 
* baseline data is biased (Jan-Feb 2020 period); 
* data has gaps (Google must ensure anonimity).  

<br>

&copy; Edoardo Giovannini 2020